definitions:
  main.ErrorResponse:
    properties:
      error_description:
        type: string
      status_code:
        type: integer
    type: object
  main.Resp:
    properties:
      response:
        properties:
          data:
            items:
              additionalProperties: true
              type: object
            type: array
          request_status:
            type: string
        type: object
    type: object
info:
  contact: {}
paths:
  /listBins/{user_id}:
    get:
      consumes:
      - application/json
      description: List bins for a user with the given parameters
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Resp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "404":
          description: Can not find ID
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "503":
          description: Service Unavailable
          schema:
            type: string
      summary: List bins for a user
      tags:
      - bins
swagger: "2.0"
